//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCake.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCake
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCake()
        {
            this.tblRecords = new HashSet<tblRecord>();
        }
    
        public int CakeID { get; set; }
        public string CakeName { get; set; }
        public int PurchasePrice { get; set; }
        public int SellingPrice { get; set; }
        public Nullable<int> CakeTypeID { get; set; }
    
        public virtual tblCakeType tblCakeType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRecord> tblRecords { get; set; }
    }
}
